config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Web UI
  scope module: 'web' do
    root 'home#index'

    # OmniAuth
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'logout', to: 'auth#logout', as: :logout

    # Repositories and checks
    resources :repositories, only: %i[index show new create] do
      resources :checks, only: %i[show create], module: :repositories
    end
  end

  # API webhook endpoint
  scope module: 'api' do
    post 'api/checks', to: 'hooks#github_webhook', as: :api_checks
  end
end

app/views/layouts/shared/_flash.html.slim
- flash.each do |type, message|
  div[class=get_alert_class(type)]
    = message
    button.btn-close[aria-label="Close" data-bs-dismiss="alert" type="button"]

app/views/layouts/shared/_head.html.slim
head
  title = t('.title')
  meta[name="viewport" content="width=device-width,initial-scale=1"]
  = csrf_meta_tags
  = csp_meta_tag
  = stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload'
  = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'
  / Use a static public icon to avoid asset pipeline dependency in tests
  link rel="icon" href="/icon.svg"

app/views/layouts/shared/_nav.html.slim
.container.mb-2
  .d-flex.flex-wrap.align-items-center.py-2.border-bottom
    .navbar.navbar-expand-md.navbar-light.me-auto
      = link_to root_path, class: 'navbar-brand me-md-4' do
        i.bi.bi-git[style='font-size: 2rem; color: OrangeRed;']
      #navbarToggler.collapse.navbar-collapse
        ul.nav.nav-pills.flex-grow-1.navbar-nav.me-auto
          li.nav-item.me-2
            = link_to t('.main'), root_path, class: 'nav-link text-dark'
          - if signed_in?
            li.nav-item.me-2
              = link_to t('.repositories'), repositories_path, class: 'nav-link text-dark'
    ul.nav.nav-pills
      - if signed_in?
        li.nav-item
          = link_to current_user.email, '#', class: 'nav-link text-secondary'
        li.nav-item
          = button_to t('.log_out'), logout_path, method: :delete, class: 'nav-link link-dark'
      - else
        li.nav-item
          = button_to auth_request_path(:github), data: { turbo: 'false' }, class: 'nav-link text-dark' do
            span.bi.bi-github.me-2
            = t('.log_in')