config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Web UI
  scope module: 'web' do
    root 'home#index'

    # OmniAuth
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'logout', to: 'auth#logout', as: :logout

    # Repositories and checks
    resources :repositories, only: %i[index show new create] do
      resources :checks, only: %i[show create], module: :repositories
    end
  end

  # API webhook endpoint
  scope module: 'api' do
    post 'api/checks', to: 'hooks#github_webhook', as: :api_checks
  end
end

app/models/repository.rb
# frozen_string_literal: true

class Repository < ApplicationRecord
  belongs_to :user, class_name: 'User', inverse_of: :repositories
  has_many :checks, class_name: 'Check', dependent: :destroy
  before_validation :assign_default_language_if_blank
  after_commit :start_initial_check, on: :create

  scope :by_owner, ->(owner_user) { where(user_id: owner_user.id) }

  validates :github_id, presence: true, uniqueness: true, numericality: { only_integer: true }

  extend Enumerize

  enumerize :language, in: %i[javascript ruby]

  private

  def assign_default_language_if_blank
    return if language.present?

    Rails.logger.debug do
      "Repository#assign_default_language_if_blank: repository_id=#{id}, language is blank, setting default to 'ruby'"
    end
    self.language = 'ruby'
  end

  def start_initial_check
    return if checks.any?(&:pending?)

    check = checks.create!
    CheckRepositoryJob.perform_later(check)
  rescue StandardError => e
    Rails.logger.error { "Failed to start initial check for repository #{id}: #{e.message}" }
    Rollbar.error(e) if defined?(Rollbar)
  end
end

app/models/repository/check.rb
# frozen_string_literal: true

class Repository
  class Check < ApplicationRecord
    before_validation :set_default_state
    before_create :ensure_repository_language
    belongs_to :repository, class_name: 'Repository', inverse_of: :checks

    validates :aasm_state, presence: true

    include AASM

    aasm do
      state :created, initial: true
      state :fetching
      state :fetched
      state :checking
      state :checked
      state :parsing
      state :parsed
      state :finished
      state :failed

      event :fetch do
        transitions from: :created, to: :fetching
      end

      event :mark_as_fetched do
        transitions from: :fetching, to: :fetched
      end

      event :check do
        transitions from: :fetched, to: :checking
      end

      event :mark_as_checked do
        transitions from: :checking, to: :checked
      end

      event :parse do
        transitions from: :checked, to: :parsing
      end

      event :mark_as_parsed do
        transitions from: :parsing, to: :parsed
      end

      event :mark_as_finished do
        transitions from: :parsed, to: :finished
      end

      event :mark_as_failed do
        transitions to: :failed
      end
    end

    def pending?
      !finished? && !failed?
    end

    private

    def set_default_state
      self.aasm_state ||= 'created'
    end

    def ensure_repository_language
      return if repository.language.present?

      Rails.logger.debug do
        "Check#ensure_repository_language: repository_id=#{repository.id}, language is nil, setting default to 'ruby'"
      end
      repository.language = 'ruby'
      repository.save!
    end
  end
end

app/controllers/web/repositories/application_controller.rb
# frozen_string_literal: true

module Web
  module Repositories
    class ApplicationController < Web::ApplicationController
    end
  end
end

app/controllers/web/repositories/checks_controller.rb
# frozen_string_literal: true

module Web
  module Repositories
    class ChecksController < Web::Repositories::ApplicationController
      before_action :authenticate_user!
      before_action :set_repository, only: %i[show create]

      def show
        @check = Repository::Check.find(params[:id])
        authorize @check
      end

      def create
        last_check = @repository.checks.last
        return redirect_to @repository, alert: t('.wait_for_the_previous_check_to_complete') if last_check&.pending?

        @check = @repository.checks.new
        authorize @check
        @check.save!

        CheckRepositoryJob.perform_later @check
        redirect_to @repository, notice: t('.check_created')
      end

      private

      def set_repository
        @repository = Repository.find(params[:repository_id])
        authorize @repository
      end
    end
  end
end

app/controllers/web/repositories_controller.rb
# frozen_string_literal: true

SUPPORTED_LANGUAGES = Repository.language.values

module Web
  class RepositoriesController < Web::ApplicationController
    before_action :authenticate_user!, only: %i[index show new create]

    def index
      authorize Repository
      @repositories = current_user.repositories
    end

    def show
      set_repository
      @checks = @repository.checks.order(created_at: :desc)
    end

    def new
      @repository = Repository.new
      authorize @repository

      filtered_repos = filter_supported_repos(user_repos_list)
      @supported_repos_for_select = filtered_repos.map { |repo| [repo[:full_name], repo[:id]] }
    end

    def create
      @repository = current_user.repositories.find_or_initialize_by(repository_params)

      if @repository.save
        authorize @repository
        RepositoryUpdateJob.perform_later(@repository, current_user.token)
        CreateRepositoryWebhookJob.perform_later(@repository)
        redirect_to repositories_url, notice: t('.repository_has_been_added')
      else
        redirect_to new_repository_path, alert: t('.repository_has_not_been_added')
      end
    end

    private

    def user_repos_list
      octokit_client = ApplicationContainer[:github_client]
      client = octokit_client.new access_token: current_user.token, auto_paginate: true
      client.repos # получение списка репозиториев
    end

    def filter_supported_repos(repos)
      repos.filter { |repo| SUPPORTED_LANGUAGES.include?(repo[:language]&.downcase) }
    end

    def set_repository
      @repository = Repository.find(params[:id])
      authorize @repository
    end

    def repository_params
      params.require(:repository).permit(:github_id)
    end
  end
end

app/views/web/repositories/_check.html.slim
tr
  td[scope="row"]
    = link_to check.id, repository_check_path(check.repository.id, check.id)
  td[scope="row"]
    = t("repo_check_states.#{check.aasm_state}")
  td[scope="row"]
    - if check.commit_id
      = link_to check.commit_id, "#{check.repository.link}/commit/#{check.commit_id}"
  td[scope="row"]
    - if check.pending?
      = t('.verification_not_completed_yet')
    - else
      = check.passed
  td[scope="row"]
    = l(check.updated_at.localtime, format: :short)

app/views/web/repositories/_form.html.slim
.mb-3
  h2 = title

= simple_form_for(@repository) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :github_id, collection: supported_repos_for_select, label: false

  .form-actions
    = f.button :submit, submit, class: 'btn btn-success mt-1'

app/views/web/repositories/_repository.html.slim
- last_check = repository.checks.last

tr
  td
    = link_to repository.name || '-', repository
  td
    = repository.language
  td
    - if last_check.nil?
      = t('.no_checks_yet')
    - elsif last_check.pending?
      = t('.verification_not_completed_yet')
    - else
      = last_check.passed
  td
    = last_check&.number_of_violations

app/views/web/repositories/edit.html.slim
== render partial: 'form', repository: @repository,
   locals: { title: t('.title'), submit: t('.submit') }

app/views/web/repositories/index.html.slim
.mb-4
  h1

= link_to t('.new'), new_repository_path, class: 'btn btn-primary'

table.table.table-striped.table-hover.mt-4
  thead
    tr
      th[scope="col"]
        = t('.name')
      th[scope="col"]
        = t('.language')
      th[scope="col"]
        = t('.result_of_the_last_check')
      th[scope="col"]
        = t('.number_of_violations')
  tbody
    == render partial: 'repository', collection: @repositories

app/views/web/repositories/new.html.slim
== render partial: 'form', repository: @repository,
   locals: { supported_repos_for_select: @supported_repos_for_select, title: t('.title'), submit: t('.submit') }

app/views/web/repositories/show.html.slim
- full_name = @repository.full_name
- repo_created_at = @repository.repo_created_at
- repo_updated_at = @repository.repo_updated_at

.mb-4
  h1
    = full_name
= link_to t('.Check'), repository_checks_path(@repository), data: { turbo_method: :post },
    class: class_names('btn btn-primary mb-4', { disabled: @repository.checks.last&.pending? })
p
  strong.me-2
    = t('.Name')
  = full_name
p
  strong.me-2
    = t('.Language')
  = @repository.language
p
  strong.me-2
    = t('.date_of_creation')
  = repo_created_at && l(repo_created_at.localtime, format: :full_month)
p
  strong.me-2
    = t('.update_date')
  = repo_updated_at && l(repo_updated_at.localtime, format: :full_month)
hr
table.table.table-striped
  thead
    tr
      th[scope="col"]
      th[scope="col"]
        = t('.check_status')
      th[scope="col"]
        = t('.commit_id')
      th[scope="col"]
        = t('.check_passed?')
      th[scope="col"]
        = t('.checked_at')
  tbody

    == render partial: 'check', collection: @checks